server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userModule
          uri: lb://USER-SERVICE
          predicates:
            - Path=/readingisgood/users/**
          filters:
            - LoggingFilter
        - id: bookModule
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/readingisgood/books/**
          filters:
            - AuthenticationFilter
            - LoggingFilter
        - id: orderModule
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/readingisgood/orders/**
          filters:
            - AuthenticationFilter
            - LoggingFilter